site_name: Yasol
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav: 
  - Home: index.md
  - Download: Download.md
  - About Yasol: About_Yasol.md
  - Instances: Instances.md
  - Q-MIPs: QMips.md
  - Credits: Credits.md
  - Contact: Contact.md 